### ISSUE TITLE
pyls_jsonrpc 这个包不存在

### ISSUE THREAD

**Issue by xunshanxiaoyao** [Wiihame/Monaco-python-lsp#8]
rt
目前有个需求，用monaco做一个python自动补全的编辑器，目前能找到类似的，貌似只有这个库，但是本地跑不起来，
pip install pyls_jsonrpc 报错，然后我去搜这个包，不存在
所以来问下，这个问题有办法解决么？
万分感谢🙏

**Comment by Wiihame** [comment]
这个包已经弃用了，需要安装另一个，不过代码里不需要修改（估计就是换了个名字）
`pip install python-jsonrpc-server`
参考的是这个：https://github.com/palantir/python-language-server/issues/643
